### ISSUE TITLE
Error command: docker-compose -f docker-compose-dev.yml up --build

### ISSUE THREAD

**Issue by mbiombani** [jonra1993/fastapi-alembic-sqlmodel-async#10]
This installer will now exit. If you understand the above warning and wish to proceed anyway, set GET_POETRY_IGNORE_DEPRECATION=1 in the environment and run this installer again.
/bin/sh: 1: poetry: not found
1 error occurred:
        * Status: The command '/bin/sh -c curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_HOME=/opt/poetry python &&     cd /usr/local/bin &&     ln -s /opt/poetry/bin/poetry &&     poetry config virtualenvs.create false' returned a non-zero code: 127, Code: 127

**Comment by jonra1993** [comment]
Hello, @mbiombani thanks for reporting this issue. This commit  https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/d5fa2526a9f545ef9c3948616664c25ac1313a4b should be solve it. Please test the latest version
