### ISSUE TITLE
Can you add example that use OSS(like minio)?

### ISSUE THREAD

**Issue by dongfengweixiao** [jonra1993/fastapi-alembic-sqlmodel-async#11]
RT.

**Comment by jonra1993** [comment]
Hello, @dongfengweixiao I hope you are having a good time. Are you suggesting that in the example endpoint on fastapi upload files and then store them on minio?

**Comment by dongfengweixiao** [comment]
Hi, @jonra1993 yep, may provide avatar field for User model.

**Comment by jonra1993** [comment]
That sounds really great @dongfengweixiao I will add this feature.

**Comment by jonra1993** [comment]
Hello @dongfengweixiao the Minio client implementation and configuration has been added here https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/ee4eae7ec0d819613b81f2053b65d80bfdd63b00

**Comment by dongfengweixiao** [comment]
> Hello @dongfengweixiao the Minio client implementation and configuration has been added here [ee4eae7](https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/ee4eae7ec0d819613b81f2053b65d80bfdd63b00)

GREATE  JOB！
