### ISSUE TITLE
May be a good idea to use snowflake as the primary key?

### ISSUE THREAD

**Issue by dongfengweixiao** [jonra1993/fastapi-alembic-sqlmodel-async#12]
RT

https://github.com/agnirudrasil/avault/blob/c6ca7037a5a99d97fcf43eb6b9ef935439171c02/backend/app/api/utils/snowflake.py

**Comment by jonra1993** [comment]
Hello, @dongfengweixiao what advantage do you expect of using snakeflake vs uuid?

**Comment by dongfengweixiao** [comment]
Hello @jonra1993 , the pros and cons can be read here: https://medium.com/geekculture/the-wild-world-of-unique-identifiers-uuid-ulid-etc-17cfb2a38fce.

Compared with the uuid v1 and the uuid v4, the v4 version has a very low probability of duplication.

**Comment by jonra1993** [comment]
Hello @dongfengweixiao thanks for the link I am going to check it

**Comment by bazylhorsey** [comment]
If this is done there is no need for the created_at column in any tables it is used, as it would be known by decoding the snowflake

**Comment by dongfengweixiao** [comment]
> If this is done there is no need for the created_at column in any tables it is used, as it would be known by decoding the snowflake

Bad idea. All field serves the business logic. The id field should only be used to mark uniqueness. Do not use the id field for additional purposes.

**Comment by jonra1993** [comment]
@dongfengweixiao @bazylhorsey I agree that using an Id like a snowflake or another timestamp base could be beneficial for better ordering, improving indexing, reducing the database size, and potentially reducing id generation time if it is less than 128 bits also the created_at column can be removed. Currently, I am doing some research and testing so in a next commit this will be implemented.

References:
https://medium.com/geekculture/the-wild-world-of-unique-identifiers-uuid-ulid-etc-17cfb2a38fce
https://medium.com/double-pointer/system-design-interview-scalable-unique-id-generator-twitter-snowflake-or-a-similar-service-18af22d74343
https://blog.devgenius.io/analyzing-new-unique-identifier-formats-uuidv6-uuidv7-and-uuidv8-d6cc5cd7391a
https://www.ietf.org/id/draft-peabody-dispatch-new-uuid-format-04.html

Implementations
https://github.com/agnirudrasil/avault/blob/c6ca7037a5a99d97fcf43eb6b9ef935439171c02/backend/app/api/utils/snowflake.py
https://github.com/SawdustSoftware/simpleflake/blob/master/simpleflake/simpleflake.py
https://github.com/sony/sonyflake
https://github.com/ergeon/python-flax-id

**Comment by bazylhorsey** [comment]
@dongfengweixiao may have a point, use your best judgment

**Comment by jonra1993** [comment]
Hello guys, after testing and looking to make the project simple to use and maintain, I have used UUID7 as the database's primary key and added some information about it on the README file including references to alternatives of IDs.
