### ISSUE TITLE
Add pgadmin autologin for dev

### ISSUE THREAD

**Issue by alldevic** [jonra1993/fastapi-alembic-sqlmodel-async#13]
Something like
https://gist.github.com/alldevic/b2a0573e5464fe91fd118024f33bcbaa

And may be Makefile for shortcuts?

**Comment by jonra1993** [comment]
Hello @alldevic I am going to check your link and add improvements on the next commit.

**Comment by jonra1993** [comment]
Hello @alldevic these shortcuts has been added in this commit https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/3269dc81124e1f0bca70c01b53e84560f9ef4c51
