### ISSUE TITLE
IUserUpdate should have id of UUID

### ISSUE THREAD

**Issue by bazylhorsey** [jonra1993/fastapi-alembic-sqlmodel-async#15]
https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/blob/a11c40077ec0bad51508974704d3343d187557a1/fastapi-alembic-sqlmodel-async/app/schemas/user_schema.py : 37

**Comment by jonra1993** [comment]
Hello @bazylhorsey thanks for report this I have solve it in this commit https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/0398985731a819e18c49ee9f640f127f805cf531
