### ISSUE TITLE
TokenType error

### ISSUE THREAD

**Issue by dongfengweixiao** [jonra1993/fastapi-alembic-sqlmodel-async#16]
https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/blob/0398985731a819e18c49ee9f640f127f805cf531/fastapi-alembic-sqlmodel-async/app/api/v1/endpoints/login.py#L68

**Comment by jonra1993** [comment]
Hello @dongfengweixiao thanks for find the error I solve it here https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/f35ca6c09e4854267874e26fe919128b145e35f0
