### ISSUE TITLE
Auth Suggestion

### ISSUE THREAD

**Issue by bazylhorsey** [jonra1993/fastapi-alembic-sqlmodel-async#17]
I see on your todo list to use KeyCloak. Might I suggest a cloud solution instead such as:
- Auth0 - highly recommend
- Cognito - good, but can get complex

Reasoning:
Keycloak is very difficult to extend off of, plus it introduces Java to the project.
Our team has played with it and we were not pleased with the results. 

I would be happy to share code on how easy it is to integrate Auth0 with FastAPI, on your project I believe it can be done in less than 20 lines of code.

**Comment by jonra1993** [comment]
Hello, @bazylhorsey I hope you are having a good time thanks any contribution is welcome. I think I can add a sample of how to use it in a future commit.
