### ISSUE TITLE
Ability to omit table joining if relations are not needed by API consumer

### ISSUE THREAD

**Issue by bazylhorsey** [jonra1993/fastapi-alembic-sqlmodel-async#20]
After turning on SQL echo, it seems that there can be quite a bit more querying than needs to necessarily happen.
Queries can be much faster if related tables are not unwrapped.

Example body param:
```
    expand_fields: Optional[bool] = Query(
        default=False, description="Expand relational fields"
    ),
```
It would be EVEN BETTER if you could only select from one of the related fields. This could easily be implemented with an additional Enum representing the base table.
Example body param:
```
    expand_fields: Optional[List[Enum[{SOMETHING}]] = Query(
        default={SOMETHING}, description="Expand relational fields"
    ),
```

In cases where the expand_fields list is empty, it should not show the unwrapped location, and more importantly not perform the selectin.

**Comment by bazylhorsey** [comment]
This also seems an appropriate time to ask why selectin was chosen as the lazy loading type?
Is there a way to change to a join at query time, this may be a good example if we can find an good spot for it.

**Comment by dongfengweixiao** [comment]
I think cancel the relationship between all tables may be more flexible, and let the program itself handle the relationship.

**Comment by bazylhorsey** [comment]
By program you mean the client consuming the API? What if a person needed in some cases to see the hero with their team, and in other cases just needed hero, and the spending time on the join was useless?

**Comment by jonra1993** [comment]
Hello @bazylhorsey the selectin was used on relationships due to the async implementation of sqlmodel I was facing this issue https://github.com/tiangolo/sqlmodel/issues/74. I agree that queries can be optimized so some joining can be omitted. What do you mean by "change to a join at query time"?

**Comment by jonra1993** [comment]
Hello @bazylhorsey lazy can also be  joined, subquery or selectin as described here https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html 

I have tested elapsed time with different lazy technique but the time is similar

```
import timeit

    elapsed_time = timeit.repeat(lambda: (await crud.hero.get_multi_paginated(params=params) for _ in '_').__anext__(), number=10, repeat=5)
    for index, exec_time in enumerate(elapsed_time, 1):
        m_secs = round(exec_time * 10 ** 6, 2)
        print(f"Case {index}: Time: {m_secs}µs")
    
    print(f"Mean: {round(max(elapsed_time)* 10 ** 6, 2)}")
```

**Comment by bazylhorsey** [comment]
https://stackoverflow.com/questions/31237042/whats-the-difference-between-select-related-and-prefetch-related-in-django-orm

Finally found a general guideline for loading techniques! :clinking_glasses: 
So it looks like M2M relations and reverse foreign keys (in your example anywhere you're doing team.heroes in crud) are best for using joined eager loading. Anywhere you have one-to-one relations or extending a model with the foreign key handy selectin is a better choice.

A colleague of mine had a solution to your bug. In your crud base you can use response.unique().scalar_one_or_none()
I am not sure if this could have undesirable results, as I know joins are an entirely different strategy than selectin and could have different results.

**Comment by jonra1993** [comment]
Hello @bazylhorsey thanks for this reference I am going to try "response.unique().scalar_one_or_none()" and see what is its output

**Comment by bazylhorsey** [comment]
I'd go for using joined in all your many-to-ones (side with foreign key), and one-to-one (both sides).
Local performance is much better as compute goes to psql.

**Comment by jonra1993** [comment]
Hello @bazylhorsey can you please share your sample code you were testing?

**Comment by jonra1993** [comment]
@bazylhorsey  Based on [loading relationships](https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html) and the insight of your link. One-One and One-Many relationships have been updated to use sa_relationship_kwargs={"lazy": "joined"} and Many-Many relationships use sa_relationship_kwargs={"lazy": "selectin"}

https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/8470af9e4a32c50ee58f1f2477f8778cc66b38a2
