### ISSUE TITLE
Cannot display is_mutual.

### ISSUE THREAD

**Issue by dongfengweixiao** [jonra1993/fastapi-alembic-sqlmodel-async#22]
https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/blob/bb8018cad75b0caf83ce248508f9d949d02bf643/fastapi-alembic-sqlmodel-async/app/api/v1/endpoints/user.py#L120

``` python
    query = (
        select(User，UserFollow.is_mutual) <- this line
        .join(UserFollow, User.id == UserFollow.user_id)
        .where(UserFollow.target_user_id == current_user.id)
    )
```
how to display is_mutual info in this query? I tried many methods, but none of them could be realized.

**Comment by jonra1993** [comment]
Hello, @dongfengweixiao mmm looks weird I am going to check it in these days.

**Comment by jonra1993** [comment]
Hello, @dongfengweixiao thanks for this insight I am going to check it also.

**Comment by jonra1993** [comment]
I see @dongfengweixiao solved this bug extracting User columns as independent fields here https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/pull/26
