### ISSUE TITLE
How to manage sub-domains?

### ISSUE THREAD

**Issue by mbnoimi** [jonra1993/fastapi-alembic-sqlmodel-async#3]
I want to modify sub-domains names and paths but I couldn't know where this template configure them?
Usually I put sub-domains confg files in `/etc/nginx/conf.d/` but I didn't see which script control them for this template!

**Comment by mbnoimi** [comment]
For example I failed to modify location of `static` path from `http://localhost/static/` to `http://localhost/static/` because there are some labels in `docker-compose.yml` control the **traefik** and **fastapi** routs

**Comment by jonra1993** [comment]
Hello, @mbnoimi this template uses traefik I plan to remove nginx in a future update. It was added to host static files but the reality is that it is not needed on the ingress.

Traefik uses routing using hostnames https://doc.traefik.io/traefik/routing/routers/ 
You can change the labels on the docker-compose file

<img width="910" alt="image" src="https://user-images.githubusercontent.com/23468720/181273045-99ef692d-1079-4958-814e-dcd0e3ca761d.png">

**Comment by mbnoimi** [comment]
> this template uses traefik I plan to remove nginx in a future update.

I totally agree with you,
BTW, does this template is production ready? If yes; May you please add deployment instructions in README.md?

>  You can change the labels on the docker-compose file. I am going to add this info on the README file

Thanks a lot

**Comment by jonra1993** [comment]
Yes it is production ready on my team we have to use it as a base to deploy on AWS using ecs but command on fastapi container should be changed by

`command: "sh -c 'alembic upgrade head && gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000 --timeout 600'"`

It is a good idea include it on README

**Comment by mbnoimi** [comment]
Thanks a lot
