### ISSUE TITLE
Convert the project

### ISSUE THREAD

**Issue by mbnoimi** [jonra1993/fastapi-alembic-sqlmodel-async#4]
I suggest to convert this repository into Github template repository or you can support `cookiecutter` for better approach to this template.

**Comment by jonra1993** [comment]
Hello, @mbnoimi  I agree with you. This is still a work in progress but I am going to add this suggestion to the todo list

**Comment by smolendawid** [comment]
My two cents are I don't think it's very useful. For a newbie, it's already hard to set everything up and see working containers locally, adding cookiecutter is another pain point and gives this feeling of having a different code locally vs remotely == having something wrong.

**Comment by jonra1993** [comment]
Hello @smolendawid yes this template can be hard for a newbie because it already uses complex tools like docker, ...
Have you tried this started template https://github.com/allient/create-fastapi-project
