### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by hacen-ai** [jonra1993/fastapi-alembic-sqlmodel-async#40]
Hello, I tried to install the project with docker with excactly same configuration on the repository. Only edit was creating .env file with same data of exemple.env and changer mycustomwebsite.com to my domain that point to my server IP. 
The issue I fascing (propably because I am an idiot): 404 page not found, when accesing the / (hello word) endpoint.
Any help/guide on how to propebly use it. Thank you verry much

**Comment by jonra1993** [comment]
Hello, @hacen-ai which server provider are you using?
