### ISSUE TITLE
Add instructions for production deployment using github actions and dockerhub (CI/CD)

### ISSUE THREAD

**Issue by hacen-ai** [jonra1993/fastapi-alembic-sqlmodel-async#43]
Hello @jonra1993 , Thank you for the amazing work.
I see that you put "Add instructions for production deployment using github actions and dockerhub (CI/CD)" on your to do list, It is excatly what I need as a bigginer, Is there any way to put it on your top todolist for the next task, will be really appreciated. 
PS: Can you make it as detailled as possible, and as readdy to use as possible, if you can of course
Thank you verry much

**Comment by jonra1993** [comment]
Hello, @hacen-ai I am really happy that this project is helpful for you. Yeah, I am going to work on that. :)
