### ISSUE TITLE
I want to use mysql(mariadb)

### ISSUE THREAD

**Issue by jakekwak** [jonra1993/fastapi-alembic-sqlmodel-async#49]
I want to use [MySQLDsn](https://github.com/pydantic/pydantic/blob/ef3cc495a9c86553b62a95a6052fd9b6ebc045e9/pydantic/networks.py) and  'mysql+asyncmy',

but I got the error message
```
 from pydantic import BaseSettings, PostgresDsn, MySQLDsn, validator, EmailStr, AnyHttpUrl
ImportError: cannot import name 'MySQLDsn' from 'pydantic' (/usr/local/lib/python3.10/site-packages/pydantic/__init__.cpython-310-x86_64-linux-gnu.so)
```

Is it possible to import MySQLDsn or MariadDBDsn.

**Comment by jonra1993** [comment]
Hello @jakekwak I have not used another DB different than Postgresql for this project I am going to check what is wrong MySQLDsn

**Comment by jakekwak** [comment]
@jonra1993 Thanks,  I checked Pydantic library.  The latest release v1.10.5 is not include the MySQLDsn and MariaDBDsn.
After the new release, I will check again.  Thanks so much.
