### ISSUE TITLE
Include locals and all defaults for vars in terraform

### ISSUE THREAD

**Issue by bazylhorsey** [jonra1993/fastapi-alembic-sqlmodel-async#50]
This snippet fails due to no locals, its hard to infer what these are. A local in variables.tf seems appropriate @jonra1993 .
```
  env_vars = {
    for obj in concat(local.fastapi, local.database, local.traefik, local.redis, local.minio, local.external_apis) : "${obj.name}" => " ${obj.value}"
  }
```

This one is not as big a deal but variables need to set by the user by putting defaults or setting it up on terraform cloud. It'd be really cool if this was all taken from .env

**Comment by jonra1993** [comment]
Hello @bazylhorsey I ma going to check it
