### ISSUE TITLE
RDS configuration terraform

### ISSUE THREAD

**Issue by bazylhorsey** [jonra1993/fastapi-alembic-sqlmodel-async#51]
It is mentioned in your docs to use a persistent database. I think it would be cool to show how to use terraform to create this.
The way it's currently set up, horizontal scaling will cause data to not be centralized. So if another instance boots, there is a 50/50 chance the data gets in the spot the user is connected to. Then, its also possible they could have data in both spots. Therefore postgres (and likely redis) should be taken out of docker-compose.yml and moved to terraform.

**Comment by jonra1993** [comment]
Hello, @bazylhorsey I agree I am going to add it in the coming days.
