### ISSUE TITLE
Question about Oso

### ISSUE THREAD

**Issue by mateoradman** [jonra1993/fastapi-alembic-sqlmodel-async#57]
Hello,

first of all, I'd like to thank you for this useful project example. I find the codebase very neat. One thing that I noticed is that you're using Oso library for authorization but I don't see it being initialised anywhere in the Python codebase. Can you please point me to where you initialise Oso, load the main.polar file, and how do you use it in the project?

Thanks! 😄

**Comment by jonra1993** [comment]
Hello, @mateoradman I really like that this project is useful for you. Sure my plan is to add some sample authz endpoints this is a current work in progress in future commits it will be implemented.
