### ISSUE TITLE
base route always returns "Hello World 2"

### ISSUE THREAD

**Issue by bazylhorsey** [jonra1993/fastapi-alembic-sqlmodel-async#58]
Looking at the code, it seems what was anticipated would it would be a sequence for every request looking like: 2, 4, 8, 16, 32, etc.
This seems to always return the same response which would indicate the global is not actually iterating as expected.
Great code by the way, I was completely unaware of async lifetimes and managing contexts.

**Comment by jonra1993** [comment]
Hello, @bazylhorsey I was thinking the same at the beginning but that middleware is in charge of resetting to default values. The context variables online exist in the context of a handler which causes this context be useful for read-only global variables for now you can check this here http://glenfant.github.io/flask-g-object-for-fastapi.html which is the base of the fastapi-global.
