### ISSUE TITLE
Remove traefik folder

### ISSUE THREAD

**Issue by webdagger** [jonra1993/fastapi-alembic-sqlmodel-async#61]
Since this has moved to using caddy, the [traefik](https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/tree/development/traefik) folder can be removed?

**Comment by jonra1993** [comment]
Hello @webdagger thanks for this reminder I have removed traefik folder in this commit
https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/60262786358bdf94bcf7ae7240ac4442069fa57b
