### ISSUE TITLE
Feature Request: Rate Limiter

### ISSUE THREAD

**Issue by jymchng** [jonra1993/fastapi-alembic-sqlmodel-async#63]
## Feature Request: Rate Limiter

Can you please help to add rate limiter to the login endpoints? Can consider using this: https://github.com/long2ice/fastapi-limiter.

Thank you.

**Comment by jonra1993** [comment]
Hello @jymchng this is a really good idea I do not think login is a good sample I am going to create some sample endpoints in which can be easy to do and if you require to login just need to replicate it. What do you think?

**Comment by jymchng** [comment]
> Hello @jymchng this is a really good idea I do not think login is a good sample I am going to create some sample endpoints in which can be easy to do and if you require to login just need to replicate it. What do you think?

Hi @jonra1993, I think that is a great idea! Yeah, maybe for some read-endpoints, these can be rate-limited. Thank you!

**Comment by jonra1993** [comment]
Hello @jymchng, this has been implemented in this commit https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/69fcf6d7836b828e862c4cb4b35ccc21604d7dbd please check natural language apis

**Comment by jymchng** [comment]
@jonra1993 Thank you for this Jonathan!
