### ISSUE TITLE
How to return a field that consolidate the attributes of other fields?

### ISSUE THREAD

**Issue by jymchng** [jonra1993/fastapi-alembic-sqlmodel-async#66]
Let's say I have a `Project` table and it has these two fields:

```
cover_img: ImageMedia = Relationship(
        sa_relationship_kwargs={
            "lazy": "selectin",
            "primaryjoin": "Project.cover_img_id==ImageMedia.id",
        }
    )

logo_img: ImageMedia = Relationship(
        sa_relationship_kwargs={
            "lazy": "selectin",
            "primaryjoin": "Project.logo_img_id==ImageMedia.id",
        }
    )
```

How do I have an extra field call `images` such that the read of a record of `Project` will return the following?

```
images: {
    'cover_img': 'UUID-1',
    'logo_img': 'UUID-2',
}
```

**Comment by bazylhorsey** [comment]
I think you could just make another schema but you'd have to reconstruct images to have the two attributes inside. This is why OOP sucks.

**Comment by jymchng** [comment]
> I think you could just make another schema but you'd have to reconstruct images to have the two attributes inside. This is why OOP sucks.

Thank you for your reply, can you provide some code snippets showing how I can achieve this? Thank you!

**Comment by jonra1993** [comment]
Hello @jymchng as I see this is possible as @bazylhorsey suggests maybe using validation which may cause the app run slow but I think an easy solution is creating a IImageMediaBasic schema with

```
class IImageMediaBasic(BaseModel):
   id: UUID
```

and in your project model schema map something like this which will cause that just UUID are returned

```
.............
    cover_img: IImageMediaBasic,
    logo_img: IImageMediaBasic,
..............
```

The disadvantage is that it will not return in a image object.


Another solution is that after you have the database response and form model you map manually to a customer response project schema like this.

```
class IProjectCustomResponse(BaseModel):
   images: dict[str, UUID]


output = IProjectCustomResponse(images={
    'cover_img': crud_response.cover_img.id,
    'logo_img': crud_response.logo_img.id,
})
```

I hope this can help.
