### ISSUE TITLE
How to connect to the Postgres database once the FastAPI is deployed into production?

### ISSUE THREAD

**Issue by jymchng** [jonra1993/fastapi-alembic-sqlmodel-async#67]
How to connect to the Postgres database once the FastAPI is deployed into production?

**Comment by jonra1993** [comment]
Hello @jymchng if you deploy to production and are using an external database you just need to setup the database host, user and password on the environment variables.

**Comment by jymchng** [comment]
Hi @jonra1993 Thank you for your reply, I don't understand it. I deployed to a private server that has a DNS Domain and residing at a specific IP address, I did not expose any port, how can I connect to the database then?

**Comment by webdagger** [comment]
If you want to do that, you will need to expose the db in the docker compose file. 
You will also need to tweak the caddy so you can access it externally

**Comment by webdagger** [comment]
Yeah. Did that work for you ?

**Comment by jymchng** [comment]
@webdagger Thanks sir for your reply, I will try it later (outside now), and let you know how it goes. :)

**Comment by jonra1993** [comment]
Hello, @jymchng  if you are using a database that is in an external server or cloud service you should add the host name of that server and make sure the port is open but if you are deploying on a server and docker handles the networks you just use "database" on the host similar as you run in local.
