### ISSUE TITLE
AuthZ with supertokens

### ISSUE THREAD

**Issue by joshung** [jonra1993/fastapi-alembic-sqlmodel-async#72]
Hi jonra1993
You are amazing when write this repo. I love it.
If posible, please change authz from oso to supertokens because I think supertokens will more interesting.
Thanks to you

**Comment by joshung** [comment]
Thanks to you for really clear explain. Continues flow your repo.

**Comment by bazylhorsey** [comment]
Just curious, how would you compare cognito to internal authn + oso?

**Comment by jonra1993** [comment]
Hello, @bazylhorsey cognito is a good tool for authN and it lacks AuthZ inbuild and oso could fit great for authZ. I think both can work together perfectly. In my opinion, AuthZ is more complicated and Oso in their documentation shows different [levels of Authz](https://www.osohq.com/academy), and you can the best that fits your project.

**Comment by bazylhorsey** [comment]
will this project include cognito at one point?

**Comment by jonra1993** [comment]
Hello @bazylhorsey I think It will not be in order to keep it the simpler possible and independent of a cloud provider. But maybe later, I can create another simpler sample using cognito auth.
