### ISSUE TITLE
Migration from Sqlmodel to SQLAlchemy 2.0

### ISSUE THREAD

**Issue by 8thgencore** [jonra1993/fastapi-alembic-sqlmodel-async#73]
The new version of SQLAlchemy 2.0 has a number of advantages, it is updated frequently. 

Sqlmodel has not released a new version since August 2022, and it is unknown when a new one will appear. The project has many problems. 

Pydantic 2 will be released soon, which will have high performance, and it is unknown when Sqlmodel will switch to it

**Comment by jonra1993** [comment]
Hello @8thgencore I understand your point but this is a really big change I think it is a good idea to wait some time before migrating from sqlmodel.

**Comment by jonra1993** [comment]
Hi @8thgencore  This is a good insight that soon we will have a SQL model updated to pydantic v2 https://www.linkedin.com/feed/update/urn:li:activity:7083138365755117568?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7083138365755117568%2C7083180443012857856%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287083180443012857856%2Curn%3Ali%3Aactivity%3A7083138365755117568%29

**Comment by 8thgencore** [comment]
[0.0.12](https://github.com/tiangolo/sqlmodel/releases/tag/0.0.12)

New version with SQLAlchemy 2.0!
