### ISSUE TITLE
Function get_multi_paginated_ordered in base_crud.py 

### ISSUE THREAD

**Issue by joshung** [jonra1993/fastapi-alembic-sqlmodel-async#74]
Hi Jonra
You and your team do amazing work. 
So but little bit problem with Function get_multi_paginated_ordered 
`if order_by is None or order_by not in columns:
order_by = self.model.id`

order_by shoud like this 
`order_by = "id"`

**Comment by jonra1993** [comment]
Hello @joshung thanks for find this issue I am going to check it and solve it

**Comment by jonra1993** [comment]
Thanks for report this issue @joshung It has been solved here https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/37e8a81df8311c84ef456eb8387ebbc6c2b827a5
