### ISSUE TITLE
make run-pgadmin fails to run.

### ISSUE THREAD

**Issue by webdagger** [jonra1993/fastapi-alembic-sqlmodel-async#75]
As documented here https://github.com/pgadmin-org/pgadmin4/issues/6475#issue-1766299018. 
Trying to run `make run-pgadmin` raises an error. I was able to circumvent the issue by disabling `  environment:
      # PGADMIN_CONFIG_SERVER_MODE: 0
      # PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 0
`
make load-server-pgadmin` raises another error related to flask. I circumvented this by adding my network in `docker-compose.yml` to `pdadmin.yml`

**Comment by jonra1993** [comment]
Hello @webdagger thanks for reporting this issue. I have solved it in this commit https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/d5a3e66215964ed8bfc22fffde6392cb9d27ddce please check it.
