### ISSUE TITLE
 db_session as argument of all methods its stupid 

### ISSUE THREAD

**Issue by h0rn3t** [jonra1993/fastapi-alembic-sqlmodel-async#8]
better use global db session contextvar, code will be cleaner

**Comment by jonra1993** [comment]
Hello, @h0rn3t thanks for your sincere feedback 👍. Maybe you agree with me that it does not exist a perfect code and there is always an opportunity to improve it ✌️🙂. The current setup is sharing a database engine and creating an independent database session in each handler (starting session and closing session after the request is handled) as is described in the official FastAPI docs [here](https://fastapi.tiangolo.com/tutorial/sql-databases/#create-a-dependency). I agree with you that if we follow the KISS and DRY principles this code can more simple. I do not think that it is a good idea that handles to share the same session instead create a pool of sessions that can be used and released for each handle as described [here](https://stackoverflow.com/questions/67403995/difference-between-connecting-to-the-database-in-app-on-eventstartup-vs-in-a). 

This recommendation will be added to the TODO list.

Reference links
https://fastapi.tiangolo.com/advanced/async-sql-databases/#connect-and-disconnect
https://github.com/tiangolo/fastapi/issues/2894
https://github.com/tiangolo/fastapi/issues/726

**Comment by h0rn3t** [comment]
```
import math
from typing import Any, Generic, Optional

from fastapi_async_sqlalchemy import db
from sqlalchemy.future import select
from sqlalchemy.sql import Select, func

from app.schemas.paginator import Page
from app.utils.types import ModelType


class CRUDBase(Generic[ModelType]):
    def __init__(self, model: type[ModelType]):
        self.model = model

    async def get(self, id: Any) -> Optional[ModelType]:
        statement = select(self.model).where(self.model.id == id)
        result = await db.session.execute(statement)
        return result.scalar_one_or_none()

    async def paginate(self, *, statement: Select, page: int = 1, size: int = 25) -> Page[ModelType]:
        total_result = await db.session.execute(select(func.count()).select_from(statement))
        total = total_result.scalar()

        pages = math.ceil(total / size)
        if page > pages:
            data = []
        else:
            search_result = await db.session.execute(statement.limit(size).offset((page - 1) * size))
            data = search_result.scalars().all()

        return Page(
            total=total,
            current_page=page,
            next_page=page + 1 if page < pages else None,
            previous_page=page - 1 if page > 1 else None,
            size=size,
            data=data,
        )
```

example how look code without dependency injection :)

**Comment by h0rn3t** [comment]
btw sorry for my word "stupid", its cool that you want to improve your code

**Comment by jonra1993** [comment]
Hello, @h0rn3t thanks for the code. I think this improvement will be beneficial. I am going to improve it as soon as possible 🙂

**Comment by jonra1993** [comment]
Thanks for this recommendation @h0rn3t. Dependency injection has been removed in this commit https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/76965146baee85642b220e1d348e3e1ba3269f1f

**Comment by JoeBerg8** [comment]
@h0rn3t do you have an example of how you set the global db session context var?
