### ISSUE TITLE
Stuck in filters

### ISSUE THREAD

**Issue by russell310** [jonra1993/fastapi-alembic-sqlmodel-async#87]
How to use filters here? If you added some examples it will be helpful. For example if we want to filter user table by first_name, last_name, email or status, How we can achieve?

**Comment by zxul767** [comment]
The documentation for `SQLModel` explains this in a lot of detail: https://sqlmodel.tiangolo.com/tutorial/where/

**Comment by jonra1993** [comment]
Hello @russell310 here you can find a couple of ways to do that https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/blob/main/backend/app/app/api/v1/endpoints/user.py at the end they are just sql queries using sqlmodel which is a layer above sqlalchemy.

This endpoint already does a search by first name and last name. It uses pg_trgm for a smarter search
<img width="853" alt="image" src="https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/assets/23468720/ff073a4b-b66d-47c0-9c07-4c71888e8763">
