### ISSUE TITLE
How to pass token for protected routes in Swagger?

### ISSUE THREAD

**Issue by nemanjam** [jonra1993/fastapi-alembic-sqlmodel-async#88]
First I logged in with `/api/v1/login`, but then browser doesn't pass Bearer token to the `/api/v1/user/list` and in UI there is no input field to pass it manually. How is this supposed to work? I can use curl, but UI should work too.

![image](https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/assets/9990165/0f8ac4df-a5b2-45ae-af38-8c304aa090e5)

**Comment by jonra1993** [comment]
Hello @nemanjam that is weird let me check

**Comment by nemanjam** [comment]
Thank you.
