### ISSUE TITLE
Few issues getting set up (DB, pgadmin, fastAPI reloading, websockets)

### ISSUE THREAD

**Issue by psycho-baller** [jonra1993/fastapi-alembic-sqlmodel-async#90]
Some background info:
- This is my first time working with docker containers
- Using a Macbook pro M1
- Used both ankane/pgvector and bitnami/postgresql:latest for the database base image

First issue I faced when I was trying to run the dev environment was [this](https://stackoverflow.com/questions/63924161/postgresql-container-not-starting-chmod-changing-permissions-of-bitnami-post) and their answer didn't fix the issue with `db_docker`. What solved it was dropping the volumes and removing [this line](https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/blob/main/docker-compose-dev.yml#L27).

Another issue I faced was running `make load-server-pgadmin`. It would complain about me not having python packages installed. I had to create a venv with [the packages that pgadmin uses](https://github.com/pgadmin-org/pgadmin4/blob/master/requirements.txt) for the command to run successfully. This is not documented in the README.

Also for some reason my dev environment wouldn't reload on change

Websockets route doesn't work with the `fastapi.localhost` url, which is what was said in [the README here](https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/tree/main#basic-chatbot-example-with-langchain-and-openai). `127.0.0.1:8000` worked

Also how do I access files from the static folder in the python code?

FYI: You can find the template that I cloned [here](https://github.com/psycho-baller/eco-enlightened/tree/main/apps/backend)

**Comment by jonra1993** [comment]
Hello @psycho-baller sorry for the delay in the reply I am going to check this in the coming days.

**Comment by thebadsektor** [comment]
> Some background info:
> 
> * This is my first time working with docker containers
> * Using a Macbook pro M1
> * Used both ankane/pgvector and bitnami/postgresql:latest for the database base image
> 
> First issue I faced when I was trying to run the dev environment was [this](https://stackoverflow.com/questions/63924161/postgresql-container-not-starting-chmod-changing-permissions-of-bitnami-post) and their answer didn't fix the issue with `db_docker`. What solved it was dropping the volumes and removing [this line](https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/blob/main/docker-compose-dev.yml#L27).
> 
> Another issue I faced was running `make load-server-pgadmin`. It would complain about me not having python packages installed. I had to create a venv with [the packages that pgadmin uses](https://github.com/pgadmin-org/pgadmin4/blob/master/requirements.txt) for the command to run successfully. This is not documented in the README.
> 
> Also for some reason my dev environment wouldn't reload on change
> 
> Websockets route doesn't work with the `fastapi.localhost` url, which is what was said in [the README here](https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/tree/main#basic-chatbot-example-with-langchain-and-openai). `127.0.0.1:8000` worked
> 
> Also how do I access files from the static folder in the python code?
> 
> FYI: You can find the template that I cloned [here](https://github.com/psycho-baller/eco-enlightened/tree/main/apps/backend)

I also am encountering issues running `make load-server-pgadmin`. Can you outline the process of creating a venv just for pgadmin? I'm not handy with docker. Hopefully you can help me out.

**Comment by jonra1993** [comment]
Hello @thebadsektor Are you facing the same error? Which computer are you using?

**Comment by jonra1993** [comment]
Hi have updated documentation and the code here https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/22da46a99a2a9ac751b74db215a5710cebb38a37 . Can you please @psycho-baller @thebadsektor check if you still have the above issues in latest version?
