### ISSUE TITLE
Sqlmodel, pydantic update

### ISSUE THREAD

**Issue by 8thgencore** [jonra1993/fastapi-alembic-sqlmodel-async#91]
A new version of Sqlmodel 0.0.14 has been released
Why not go to Pydantic 2?

**Comment by jonra1993** [comment]
Hello @8thgencore  Yes I am going to work in that this weekend.

**Comment by jonra1993** [comment]
Hi @8thgencore please check this commit https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/2a9bd83f71ab928a658dc4c69d31947e1fd04a1c. It add compatibility with latest pydantic and sqmlodel
